name: iso_build
on:
  schedule:
    - cron:  '2 2 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [iso_profile_update]

jobs:
  prepare-release:
    runs-on: ubuntu-20.04
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}
  build-release:
    runs-on: ubuntu-20.04
    needs: [prepare-release]
    strategy:
      matrix:
        EDITION: [sway]
        BRANCH: [stable]
        SCOPE: [full]
        KERNEL: [linux510, linux514]
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: import sway key
        run: |
          gpg --keyserver keys.openpgp.org --receive-keys ${{ secrets.GPG_KEYID }}
      - name: image-build-upload
        uses: Manjaro/manjaro-iso-action@v2.5
        with:
          iso-profiles-repo: https://github.com/Manjaro-Sway/iso-profiles
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          kernel: ${{ matrix.kernel }}
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
          additional-trusted-gpg: ${{ secrets.GPG_KEYID }}
      - name: rollback
        if: ${{ failure() || cancelled() }}
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
          git push --delete origin ${{ needs.prepare-release.outputs.release_tag }}
