name: gh pages

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - build_pages

concurrency: 
  group: "pages-deployment"
  cancel-in-progress: true

jobs:
  pages:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: download default iso
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        LATEST_RELEASE=$(gh release list --limit 1 --exclude-drafts | sed -e 's/\s.*$//')
        gh release view ${LATEST_RELEASE} --json assets --jq '[.assets[] | .publishedUrl = "https://manjaro-sway.download/manjaro-sway/\(.name)" | select(.name | contains("minimal") or contains("unstable") | not)]' >docs/assets.json
        
        mkdir -p docs/manjaro-sway
        cat docs/assets.json | jq '.[].url' | xargs wget -q -P docs/manjaro-sway
        
        sudo apt-get update
        sudo apt-get install mktorrent

        mktorrent -v -a udp://tracker.opentrackr.org:1337 -l 21 \
          -n "manjaro-sway" -w https://manjaro-sway.download/ \
          -o docs/manjaro-sway/manjaro-sway.torrent \
          docs/manjaro-sway
        
        ls -l docs/*
    - name: upload github pages
      uses: actions/upload-pages-artifact@v1.0.3
      with:
        path: './docs'
    - name: deploy github pages
      id: deployment
      uses: actions/deploy-pages@v1.0.10
